"""
Django settings for givres project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ns-wc41^yk+gh5#_*$ke-bf!tatom62v#20bwq4p7l(w9%g!b8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", ]

# MEDIA & STATIC
MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'media'))
# MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'media') # kart_env/kart/../media
STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'static'))

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
